repos:
- repo: https://github.com/ambv/black
  rev: 24.4.2
  hooks:
    - id: black
      language_version: python3.8
      exclude: ^src/migrations/

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      exclude: ^src/migrations/
